spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/credit_service
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - health
          - logfile
          - hystrix.stream
logging:
  file: target/app.log