DROP TABLE IF EXISTS CREDIT_DOCUMENT;

CREATE TABLE IF NOT EXISTS CREDIT_DOCUMENT (
  ID				        INT PRIMARY KEY AUTO_INCREMENT,
  SAVE_TIME         TIMESTAMP,
  BOR_NAME          VARCHAR(100),
  BOR_LY_INCOME     DOUBLE,
  BOR_APPR_STATUS   BOOLEAN,
  FP_NAME           VARCHAR(100),
  FP_AGE            DOUBLE,
  FP_EXPERIENCE     DOUBLE,
  FP_APPR_STATUS    BOOLEAN,
  CREDIT_PRODUCT    VARCHAR(50),
  REQ_SUM           DOUBLE,
  REQ_PERCENT       DOUBLE,
  REQ_TERM          DOUBLE,
  APPR_SUM          DOUBLE,
  APPR_PERCENT      DOUBLE,
  APPR_TERM         DOUBLE
);
