CREATE SEQUENCE IF NOT EXISTS CREDIT_DOCUMENT_ID_SEQ;

CREATE TABLE IF NOT EXISTS CREDIT_DOCUMENT (
  ID				        INT PRIMARY KEY DEFAULT NEXTVAL('CREDIT_DOCUMENT_ID_SEQ'),
  SAVE_TIME         TIMESTAMP,
  BOR_NAME          VARCHAR(100),
  BOR_LY_INCOME     REAL,
  BOR_APPR_STATUS   INT,
  FP_NAME           VARCHAR(100),
  FP_AGE            REAL,
  FP_EXPERIENCE     REAL,
  FP_APPR_STATUS    INT,
  CREDIT_PRODUCT    VARCHAR(50),
  REQ_SUM           REAL,
  REQ_PERCENT       REAL,
  REQ_TERM          REAL,
  APPR_SUM          REAL,
  APPR_PERCENT      REAL,
  APPR_TERM         REAL
);
